print("%d" %123)
print("%5d" %123)
print("%05d" % 123)
print("%f" % 123.45)
print("%7.1f" % 123.45)
print("%s" % "파이썬")
print("%10s" % "Python")
print("\n줄 바꿈\n연습")
print("\t 탭키 \t연습")
print("글자가 \"강조\" 되는 효과")
print("\\\\\\ 역슬래시 세개 출력")
print(r"\n\t''\\를 그대로 출력")